### ISSUE TITLE
Retrieving game data for scripts

### ISSUE THREAD

**Issue by RLangridge** [dotprologue/ScenarioFlow#2]
Hi there. I've been playing around with ScenarioFlow for a little while now. I was wondering if I've missed something here; in my scenario flow script I want to retrieve some data from my game. An example of this would be the following:

Player reaches decision point A: decision point A usually has two choices: X or Y. When player has item H (retrieved from game data), they are given three choices: X, Y and Z. 

Does scenario flow have this sort of functionality via its scripts (i.e. the ability to retrieve data from the game and store it as a script variable) or should I instead be making multiple scripts for cases like this? (e.g. instead of having one script for the above condition, I have two scripts, one has choices X and Y and the other script has choices X, Y and Z and I determine which one to run via Unity)?

Thank you for your time

**Comment by ito-akira-dp** [comment]
Hello, RLangridge! Thank you for your question.

Firstly, you can't store any values as variables in scenario flow scripts. The role of a scenario flow script is simply to call C# methods, but it doesn't care of the return values at all.

Secondly, you don't need to create multiple scripts to achieve your goal. As mentioned earlier, one task of a scenario flow script is to call C# methods as commands. So you can handle variables in C# scripts instead of scenario flow scripts.

In your example, you want to switch the number of choices given to the player depending on whether the player has the specific item. Then, what you are going to do is to create a command that refers to the player's status regarding the retrieved items to switch its behavior **in a C# script**.
For example:
``` cs
public class PlayerDecisionMaker : IReflectable
{
    IItemStatusReader itemStatusReader;
    ILabelOpener labelOpener;

    [CommandMethod("show 2-3 choices on item")]
    [Snippet("{${1:choice1}}: {${2:label1}}")]
    [Snippet("{${3:choice2}}: {${4:label2}}")]
    [Snippet("------ If the player has {${5:item}} ------")]
    [Snippet("{${6:choice3}}: {${7:label3}}")]
    public async UniTask ShowTwoOrThreeChoicesOnItem(
        string choice1, string label1,
        string choice2, string label2,
        string item,
        string choice3, string label3,
        CancellationToken cancellationToken)
    {
        var choices = new string[] { choice1, choice2, choice3 };
        var labels = new string[] { label1, label2, label3 };
        var answerNum = itemStatusReader.HasItem(item) ?
            await ShowChoicesAsync(choices, cancellationToken) :
            await ShowChoicesAsync(choices.Take(2), cancellationToken);
        labelOpener.OpenLabel(labels[answerNum]);
    }

    private UniTask<int> ShowChoicesAsync(IEnumerable<string> choices, CancellationToken cancellationToken)
    {
        // Show choices, and wait for the player's decision
        // Return the index of the selected choice 
        // (e.g. 0/1 is returned if the player selects the 1st/2nd choice)
        return UniTask.FromResult(0);
    }
}

public interface IItemStatusReader
{
    bool HasItem(string itemName);
}
```
![image](https://github.com/user-attachments/assets/4060b2c3-083b-4de2-bf3f-35b702c8da6a)

The `ILabelOpener` interface and its implementation are provided by ScenarioFlow. You have to develop the `ITemStatusReader` interface, its implementation, and the `ShowChoicesAsync` method by yourself.

**Comment by RLangridge** [comment]
Thank you for your time, I think I have an idea as to what I want to do with this now. I can create a command for asking questions that takes in a singular argument which will be the name of a question. I'll then look up that question and its potential answers and criteria for providing answers (e.g. if a player has an item or not) and add such things into a scriptable object for ease of use.

Thank you again, I really do enjoy this framework.
